marvel_character/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from marvel_character.forms import UserLoginForm
from marvel_character.models import User, db, check_password_hash 

from flask_login import login_user, logout_user, current_user, login_required


auth = Blueprint('auth', __name__, template_folder='auth_templates')


@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    userform = UserLoginForm()

    try:
        if request.method == 'POST' and userform.validate_on_submit():
            email = userform.email.data
            username = userform.username.data
            password = userform.password.data
            print(email, password)

            user = User(email, username, password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('auth.signin'))
        
        
    except:
        raise Exception('Invalid Form Data. Please Check your form')
    
    return render_template('signup.html', form=userform)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    userform = UserLoginForm()


    try:
        if request.method == "POST" and userform.validate_on_submit():
            email = userform.email.data
            username = userform.username.data
            password = userform.password.data 
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in via: Email/Password', 'auth-success')
                return redirect(url_for('site.profile')) #Come back to here and redirect to profile 
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
            
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signin.html', form=userform )


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

marvel_character/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from marvel_character.forms import CharacterForm
from marvel_character.models import Character, db 

site = Blueprint('site', __name__, template_folder='site_template')

@site.route('/')
def home():
    print('look at this cool project. Would you just look at it')
    return render_template('index.html')

@site.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    marvelform = CharacterForm()

    try:
        if request.method == 'POST' and marvelform.validate_on_submit():
            fname = marvelform.fname.data
            lname = marvelform.lname.data
            superhero_name = marvelform.superhero_name.data
            description = marvelform.description.data
            weakness = marvelform.weakness.data
            normal_job = marvelform.normal_job.data
            team = marvelform.team.data
            gender = marvelform.gender.data
            user_token = current_user.token 

            character = Character(fname, lname, superhero_name, description, weakness, normal_job, team, gender,  user_token)
            
            db.session.add(character)
            db.session.commit()

            return redirect(url_for('site.profile'))
        
    except:
        raise Exception('Character not created, please check your form and try again.')
    
    user_token = current_user.token 
    characters = Character.query.filter_by(user_token=user_token)

    return render_template('profile.html', form=marvelform, characters=characters)

marvel_character/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Character Inventory API</title>
</head>
<body>

        <!-- NavBar Here -->
        <nav class="ct-nav">
            <div>
                <img src="../static/images/superheros.jpg" alt="Superhero Characters Logo">
            </div>

            <div>
                <ul id="horizontal-list">
                    <a href="{{ url_for('site.home') }}">
                        <li>The Coding Characters Project</li>
                    </a>
                    <a href="{{ url_for('site.home') }}">
                        <li>Home</li>
                    </a>
                    {% if current_user.is_authenticated %}
                    <a href="{{ url_for('site.profile')}}">
                        <li>Profile</li>
                    </a>
                    <a href="{{ url_for('auth.logout')}}">
                        <li>Log Out</li>
                    </a>
                    {% else %}
                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Sign Up Free</li>
                    </a>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <!-- End Nav Bar -->

        {% block content %}
        {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

marvel_character/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class='form-control', placeholder = "Place Username Here...")}}
        </fieldset>

        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class='form-control', placeholder = "Place Email Here...")}}
        </fieldset>

        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class='form-control', placeholder = "Place Password Here...")}}
        </fieldset>

        <!-- Submit Button Field -->
        {{ form.submit_button(class='btn btn-primary btn-block')}}
    </div>
</form>

marvel_character/templates/marvelform.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset class="fname-field">
            {{ form.fname.label }}
            {{ form.fname(class='form-control', placeholder='First Name') }}
        </fieldset>
        <fieldset class="lname-field">
            {{ form.lname.label }}
            {{ form.lname(class='form-control', placeholder='Last Name') }}
        </fieldset>
        <fieldset class="superheroname-field">
            {{ form.superhero_name.label }}
            {{ form.superhero_name(class='form-control', placeholder='Superhero Name') }}
        </fieldset>
        <fieldset class="description-field">
            {{ form.description.label }}
            {{ form.description(class='form-control', placeholder='Description') }}
        </fieldset>
        <fieldset class="weakness-field">
            {{ form.weakness.label }}
            {{ form.weakness(class='form-control', placeholder='Weakness') }}
        </fieldset>
        <fieldset class="normaljob">
            {{ form.normal_job.label }}
            {{ form.normal_job(class='form-control', placeholder='Normal Job') }}
        </fieldset>
        <fieldset class="team-field">
            {{ form.team.label }}
            {{ form.team(class='form-control', placeholder='Superhero Team') }}
        </fieldset>
        <fieldset class="gender-field">
            {{ form.gender.label }}
            {{ form.gender(class='form-control', placeholder='Gender') }}
        </fieldset>

        {{ form.submit_button(class='btn btn-primary btn-block mt-2')}}
    </div>
</form>